name: Package Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
        
permissions:
    # Enable the use of OIDC for npm provenance
    id-token: write
    # Enable the use of GitHub Packages registry
    packages: write
    # Enable `semantic-release` to publish a GitHub release and post comments on issues/PRs
    contents: write
    issues: write
    pull-requests: write

jobs:
  release-and-publish:
    name: Release & Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "node"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Run automated package publishing
        id: semantic-release
        run: |
          pnpx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_EMAIL: jerrymonkeynj@163.com
          GIT_AUTHOR_NAME: jerrywcy
          GIT_COMMITTER_EMAIL: jerrymonkeynj@163.com
          GIT_COMMITTER_NAME: jerrywcy
